### PR TITLE
Fixes for compile failures and warnings and test breaks vs HTSJDK master

### PR DESCRIPTION
**Pull request by tfenne**
This PR fixes a number of issues against HTSJDK master.  I'm not sure what the process is for merging this (once reviewed), but I think the scope of this PR shows that the current system of building Picard off a fixed HTSJDK version also has some problems - specifically the authors of PRs in HTSJDK can leave Picard in a bad state.  It was now unclear to me how one would go about taking a non-release version of HTSJDK and finding an appropriate version of Picard that it would work with - something that is essential given the number of downstream projects that depend on _both_ together.

The changes in this PR are:
1. Fixes for @akiezun's changes to Histogram
2. Fix to no longer call non-existent IntelDeflator method for logging
3. Replace @yfarjoun's use of `_` variable names in `CollectIndependentReplicateMetrics` to reduce compiler warnings
4. Change the test data for @yfarjoun's _independent replicates_ tests to not have flag fields with leading `0`s, since that now causes exceptions when reading (probably due to @nh13's flag field changes in HTSJDK, but I didn't look).

### CODE REVIEW

**Comment by tfenne** [comment]
@jacarey, @ktibbett, @lbergelson: what's the procedure for handling something like this?  Master currently builds against HTSJDK `2.4.1`, but fails miserably against `master`.  But if this gets merged, it will fail against `2.4.1`.

**Comment by yfarjoun** [comment]
👍  on the code changes. Thanks @tfenne.

I don't know how to do the merging release. perhaps we need to cut a release?

**Comment by tfenne** [comment]
Thanks @yfarjoun - I'm not sure either.  I think that perhaps it would be beneficial to have a `dev` or `on-htsjdk-master` branch where changes like this can be merged more rapidly, and which is then merged into master prior to release.  But I'm not sure what folks had in mind when the switch was made to use non-master HTSJDK.

**Comment by yfarjoun** [comment]
my understanding is that @jacarey is working on a solution and that the
current interm period is the victim of the gap between changing the build
system on htsjdk and doing the same in picard.

**Comment by tfenne** [comment]
@yfarjoun That would be good if that's the case, because the current situation is no fun!

**Comment by jacarey** [comment]
That is correct I'm working on a gradle version of the picard build that can pull locally published htsjdk to allow for easier development against master and feature branches. I'm hoping to finish that up this week or early next week.

**Comment by tfenne** [comment]
Thanks @jacarey. Since it's been ~3 weeks since the last release, what do you think about doing the following sooner rather than later?:

- Release HTSJDK 2.5
- Merge this PR
- Release Picard 2.5

**Comment by jacarey** [comment]
@tfenne That is fine with me. @lbergelson can you do this release?

**Comment by lbergelson** [comment]
@jacarey I'll do it.  I might bug you if we have issues, but I don't expect any.

**Comment by jacarey** [comment]
thanks @lbergelson hopefully the next release will just be using gradle

**Comment by droazen** [comment]
@tfenne Once @jacarey's PR is in we'll put together documentation with suggested workflows that we hope will satisfy all use cases, both for projects using htsjdk as a standalone dependency and those working in the htsjdk + picard ecosystem. In particular we want to make sure that we can easily:

-Release htsjdk independently of picard.
-Move picard master to a snapshot of htsjdk master when necessary (eg., an immediate htsjdk release is not possible for some reason). We do already automatically publish continuous snapshots of htsjdk master to maven.
-Depend on an arbitrary branch/build of htsjdk from a branch of picard when doing local development.

**Comment by lbergelson** [comment]
I'm getting an error building this branch on the current htsjdk master.

`CollectAlignmentSummaryMetrics.testChimeras`

```
htsjdk.samtools.SAMFormatException: Error parsing text SAM file. MAPQ should be 0 for unmapped read.; File /Users/louisb/Workspace/picard/testdata/picard/sam/summary_alignment_stats_test_chimeras.sam; Line 12
Line: SL-XAV:1:1:0:764#0/1	0177	chr1	10	255	6M	chr1	1	10	TTCATG	&/,&-.	OT:Z:normal

	at htsjdk.samtools.SAMLineParser.reportErrorParsingLine(SAMLineParser.java:457)
	at htsjdk.samtools.SAMLineParser.parseLine(SAMLineParser.java:355)
	at htsjdk.samtools.SAMTextReader$RecordIterator.parseLine(SAMTextReader.java:248)
	at htsjdk.samtools.SAMTextReader$RecordIterator.next(SAMTextReader.java:236)
	at htsjdk.samtools.SAMTextReader$RecordIterator.next(SAMTextReader.java:212)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:545)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:519)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:129)
	at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:77)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:208)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:100)
	at picard.cmdline.CommandLineProgramTest.runPicardCommandLine(CommandLineProgramTest.java:48)
	at picard.analysis.CollectAlignmentSummaryMetricsTest.testChimeras(CollectAlignmentSummaryMetricsTest.java:521)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by lbergelson** [comment]
So, what's happening here is I believe as follows...  The test has a samfile which has the samflags 0177.  Previously this was interpreted as the decimal value 0177 which is the same as treating it as.  With the changes @nh13 made to samflag inputs, this is now treated as octal 177 or decimal 127.  

Without the leading 0 the digits flags 177 would be parsed correctly, I guess the question is, is a leading 0  on the samflags field legal?  I didn't see anything in the spec either way.  Is a leading 0 there common

**Comment by lbergelson** [comment]
@tfenne @jacarey Release is waiting on the response to this.

**Comment by tfenne** [comment]
Sorry @lbergelson I was away from the computer for a while.  I'm not sure about the legality of leading zeros in the flag field, but I'm pretty sure it's un-common and likely only to exist in hand-crafted files.

I'll modify that file and push an update to this branch, and then we can separate the conversation about what we'd like the code to do from getting the release out.  @nh13 I think this is your commit affecting the flag fields, so perhaps you'd like to weigh in?

**Comment by tfenne** [comment]
@lbergelson I've fixed the offending `.sam` locally, and pushed the update here, but I'm still running tests locally to see if anything else fails.

**Comment by lbergelson** [comment]
@tfenne Thanks for the update!  

I assume the leading 0 is a weird edge case, but if there are files out there that have that they'll not work properly with a new htsjdk since that now indicates that it's in octal.  Maybe we should change the octal representation of the samflags field to use 0o /0O as it's identifier.  Java uses the 0 prefix, which has this ambiguity problem, but Ocaml for instance uses 0O.  Probably not compatible with the c implementations though.

**Comment by tfenne** [comment]
@lbergelson @nh13 It's only a problem for text-sam, and even then I think most implementations will just write the integer without leading `0`s.  But I have to admit, I find the utility of octal flag fields to be zero personally!  I can understand wanting hex or the string representation, but I wonder if anyone finds octal useful?

**Comment by tfenne** [comment]
Ok - all my tests pass locally.  The branch here is failing still due to being stuck on the wrong version of HTSJDK.

**Comment by lbergelson** [comment]
Thanks.  I'll release then.

**Comment by tfenne** [comment]
@droazen Thanks for the explanation - that sounds great.  I spent a little time playing with the HTSJDK build for various purposes and ended up getting `gradle install` to work to publish a snapshot locally.  I've done some googling, but came up dry: do you know if it's possible to configure gradle to publish to a local `ivy` repo instead of a local `maven`/`m2` repo?  I have a ton of `sbt` based projects which publish to a local ivy repo, and having them pull from two different local repos seems like a recipe for disaster at some point.

**Comment by droazen** [comment]
@tfenne There does appear to be an `ivy-publish` plugin for gradle that we could try out (https://docs.gradle.org/current/userguide/publishing_ivy.html) If it works, perhaps we could have some kind of toggle in the build system to tell gradle whether to publish to local maven or local ivy.

**Comment by jmarshall** [comment]
The spec describes SAM's FLAG field as an `Int` in the range [0, 2<sup>16</sup>-1], but is silent about how that integer is represented in text.  In practice, whatever the spec has said, samtools has always (that's both 0.1.x and htslib-based) parsed this field with `strtol(…, 0)` — which accepts hex `0[xX]…` / octal `0…` / decimal otherwise.

So, to the extent that there exist leading-0-flag-field SAM files in the wild outwith Picard's test suite, prior to Nils's PR they were being interpreted differently by the C and Java SAM implementations.  Therefore we can conclude that they have not existed outwith Picard's test suite…

Whatever we think the modern world utility of octal is :smile:, on the principle that the spec reflects existing practice in the implementations, I think the correct course of action is to remove the leading 0 in these test files (done), and (if we were to spell this out in the spec) specify the leading `0[Xx]` hexadecimal / leading `0` octal / symbolic starting with non-digit / otherwise decimal behaviour.

**Comment by lbergelson** [comment]
@jmarshall Thanks for the comments.  I'd support making the spec more explicit like you've described.

**Comment by nh13** [comment]
I also support updating the spec.

**Pull request merged**
