### PR TITLE
Remove deprecated classes

### PR DESCRIPTION
**Pull request by ronlevine**
### Description

Implements https://github.com/broadinstitute/picard/issues/510.
Removes the deprecated classes and associated tests for:
* CollectWgsMetricsFromQuerySorted
* CollectWgsMetricsFromSampledSites 
* GenotypeReader
* CalculateHsMetrics 

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [X] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [X] All tests passing on Travis

#### Review
- [X] Final thumbs-up from reviewer
- [X] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by ronlevine** [comment]
@eitanbanks Please review.

**Comment by eitanbanks** [comment]
It does in fact look like you've removed the deprecated classes and associated test data, so I can give a thumbs up for that.  I can also attest that the CollectWgsMetrics classes are ready to be stricken from the codebase.
But I'm not connected to the other 2 tools so maybe we should get a thumbs up from @yfarjoun?

**Comment by ronlevine** [comment]
Ping @yfarjoun

**Comment by yfarjoun** [comment]
@ktibbett can you find a reviewer for this?

**Comment by kshakir** [comment]
Proxying for @ktibbett: Looks good to us!

**Pull request merged**
