### PR TITLE
Bug fix: CollectWgsMetricsWithNonZeroCoverage fails to produce a plot

### PR DESCRIPTION
**Pull request by nh13**
when there is zero coverage.

Also fixed up a few warnings.

### CODE REVIEW

**Comment by nh13** [comment]
@yfarjoun or @lbergelson, care to take a look?  This happens when we have zero coverage data (yikes!).

**Comment by nh13** [comment]
@yfarjoun good idea, I added in a test to make sure the pdf is created.   I squashed the commits to be ready for the merge.

**Comment by yfarjoun** [comment]
Thanks. in the future, please refrain from squashing. We can easily squash in github and it only makes reviewing more difficult. (in this case, it's really not a problem since the changes are so minimal...)

**Comment by yfarjoun** [comment]
Looks great! thanks for the fix and test!

👍

**Pull request merged**
