### PR TITLE
fix Exception thrown in MergeBamAlignment when NM tag was present 

### PR DESCRIPTION
**Pull request by yfarjoun**
..and alignment information was copied out to tag.

Added tests specifically covering this use-case.

### Description

_Give your PR a **concise** yet **descriptive** title_
_Please explain the changes you made here._
_Explain the **motivation** for making this change. What existing problem does the pull request solve?_
_Mention any issues fixed, addressed or otherwise related to this pull request, including issue numbers or hard links for issues in other repos._
_You can delete these instructions once you have written your PR description._

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by eitanbanks** [comment]
One request: could you please have at least some test data where the NM value is not 0?  I just want to see it tested with a positive value.

**Comment by yfarjoun** [comment]
thanks, @eitanbanks. I added a non-zero NM, and also decided that if the user asked that the alignment information be *moved* to the tag (as opposed to _copied_) then the NM needs to be removed from the record...so I made the changes to do that.

**Comment by eitanbanks** [comment]
You know, it might be nice to add a quick comment explaining what's happening in that line since it's a little dense...

**Comment by yfarjoun** [comment]
better?

**Comment by eitanbanks** [comment]
Yes!

**Pull request merged**
