### PR TITLE
Dekling website fixes

### PR DESCRIPTION
**Pull request by dekling**
Changes to Index, Overview, and Building pages.

### CODE REVIEW

**Comment by vdauwera** [comment]
@geoffjentry Is Travis expected to run successfully on the gh-pages branch?

**Comment by geoffjentry** [comment]
@vdauwera Dunno although I'd guess either "no" or "it doesn't matter". I saw on hipchat that travis was having some problems earlier as well which could be related.

**Comment by geoffjentry** [comment]
@jacarey - looks like you were the last one to commit to gh-pages, do you know if travis is supposed to work there/

**Comment by jacarey** [comment]
gh pages is commited to every time we do a release.. i didn't even know travis was building it.. .can we add it as an ignored branch?

**Comment by vdauwera** [comment]
@dekling I made some additional changes. Remind me to show you how the code allows us to add the auto-generated docs at build time. 

@jacarey @geoffjentry Do you guys know if it's possible to preview the changes before merging?

**Comment by geoffjentry** [comment]
I did some googlin' and came up with this: http://stackoverflow.com/questions/24271225/how-do-you-view-a-different-branch-of-your-github-pages

Probably not what you were hoping for

**Comment by vdauwera** [comment]
Urk. Thanks. I'm going to see if I can workaround that by forking the repo and seeing if it will display the website from my fork.

**Comment by pgrosu** [comment]
Hi Geraldine,

Here is something that might help:

1) If you go under the [Commits](https://github.com/broadinstitute/picard/pull/420/commits) tab, and look at the latest commit - the one which is at the most bottom - you will see a number that looks like this:

[11877c1](https://github.com/broadinstitute/picard/commit/11877c18be9ccca8aaeed2dd415a18940195ddcb)

2) If you click on it, then you will get to the most up-to-date version of commits for this PR.

3) Next you will see a button towards the upper-right that says the following:

[Browse Files](https://github.com/broadinstitute/picard/tree/11877c18be9ccca8aaeed2dd415a18940195ddcb)

4) Click on that button, and you will see the repository of this PR.  In it you will see the [index.html](https://github.com/broadinstitute/picard/blob/11877c18be9ccca8aaeed2dd415a18940195ddcb/index.html) file.

5) Click on the [index.html](https://github.com/broadinstitute/picard/blob/11877c18be9ccca8aaeed2dd415a18940195ddcb/index.html) file, and copy the address in the browser, which should look like this:

https://github.com/broadinstitute/picard/blob/11877c18be9ccca8aaeed2dd415a18940195ddcb/index.html

6) To preview what the page will generally look like, take the above link and add it to the question mark of the following link:

http://htmlpreview.github.io/?

Then to preview your PR, you would use the following concatenated link in a browser address:

http://htmlpreview.github.io/?https://github.com/broadinstitute/picard/blob/11877c18be9ccca8aaeed2dd415a18940195ddcb/index.html

Hope it helps,
~p

**Comment by vdauwera** [comment]
Thanks @pgrosu, but I need to see what it actually looks like with all the formatting applied. 

The good news is the the for idea totally works -- I had to do a merge (though I think a direct commit would work too) on the gh-pages to trigger a rebuild, but here it is in its full glory: http://vdauwera.github.io/picard/

**Comment by vdauwera** [comment]
This already tells me part of what I needed to know: the h3 styling doesn't look very good and I need to tweak the code styling because the theme doesn't differentiate well between code blocks and section headers.

**Comment by pgrosu** [comment]
@vdauwera That is another way :)  It looks totally awesome!

**Comment by vdauwera** [comment]
Thanks @pgrosu :) 

I think we can do better though -- will try a few things in my fork.

**Comment by vdauwera** [comment]
@yfarjoun @ktibbett We made a big push to freshen up the static html on the Picard docs site. Would you like to review or assign someone to do so? I have a staged version on a fork here: http://vdauwera.github.io/picard/index

Note that if you follow links they will take you back to the live broadinstitute.github.io version, so you'll need to substitute `vdauwera` for `broadinstitute` at the base of the url.

**Comment by vdauwera** [comment]
After discussion with @ktibbett, I'm taking complete ownership (and therefore responsibility) for the end-user documentation website. 

This PR (which I'm about to merge) intends to improve user experience. There should be no breaking changes (if anyone bookmarked any links they should still work) and the layout changes should not be too disruptive to users who are already familiar with the website. However, some of the content changes are fairly substantial (esp. homepage and overview page) so all feedback on the revamped pages is very welcome. Since this branch doesn't touch the program code at all, we can make modifications rapidly if anyone has strong feelings about some of the changes we've made here.

**Comment by dekling** [comment]
👍
> On Feb 19, 2016, at 8:59 PM, Geraldine Van der Auwera <notifications@github.com> wrote:
> 
> Merged #420 <https://github.com/broadinstitute/picard/pull/420>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/broadinstitute/picard/pull/420#event-557341044>.
> 

--
David E. Kling, Ph.D.
Scientific/Technical Writer
Broad Institute
75 Ames Street, #7003X
Cambridge, Ma  02142
O (617) 714-7351
C (617) 291-1617

**Pull request merged**
