### PR TITLE
Fixes CheckIlluminaDirectory problem with cbcl files and skips in the READ_STRUCTURE

### PR DESCRIPTION
**Pull request by nnordborg**
### Description

This is a possible fix for issue https://github.com/broadinstitute/picard/issues/1485

The problem is that the 'key' variable in the loop is not the same as the 'cycle' if there are skips in the READ_STRUCTURE. This causes the file size check to check files that belong to skipped cycles and the result is that CheckIlluminaDirectory fails with an error message. 

The fix uses the array returned by outputMapping.getOutputCycles() to lookup the correct 'cycle' number.

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by gbggrant** [comment]
Looks good @nnordborg - I've verified that this fixes similar behavior we've seen on our Novaseqs. 

Any chance you can add a test case for this?

**Comment by nnordborg** [comment]
Thanks for looking into this. Regarding a test case, I am not sure if I am able to do that. I have looked at the code in CheckIlluminaDirectoryTest and if I understand it correctly it seems like it generates temporary fake files that are tested. The IlluminaFileUtilTest.makeFiles() doesn't have any option for Cbcl files.

There are files available in tetsdata/picard/illumina/151T8B8B151T_cbcl, so maybe it would be possible to use them. But I can't get them to validate when I test by manually running CheckIlluminaDirectory:

`java -jar picard.jar CheckIlluminaDirectory BASECALLS_DIR=testdata\picard\illumina\151T8B8B151T_cbcl\Data\Intensities\BaseCalls\ READ_STRUCTURE=1T LANES=1 DATA_TYPES=BaseCalls`

I get:
Exception in thread "main" picard.PicardException: File [testdata\picard\illumina\151T8B8B151T_cbcl\Data\Intensities\BaseCalls\L001\C1.1\L001_1.cbcl, testdata\picard\illumina\151T8B8B151T_cbcl\Data\Intensities\BaseCalls\L001\C1.1\L001_2.cbcl] is not the expected size of 68 instead it is 69

I have tried to understand why this is happening and have found that the expected and and actual sizes that are compared are calculated from the **file sizes**, the **header size** and the **compressed block size**. The CbclReader is reading the header and compressed block size from the cbcl files and both L001_1.cbcl and L001_2.cbcl have headerSize=65 and compressedBlockSize=34 which should mean that the file size must be 99 bytes. But L001_1.cbcl is 100 bytes so the comparison in CheckIlluminaDirectory fails. 

I have tested some of the other cycle directories as well, and in those where both cbcl files are 99 bytes (for example C2.1 and C4.1) CheckIlluminaDirectory reports SUCCEEDED!

So, it could be that some cbcl files have an extra byte that should be removed, or it could be incorrect header values, or there is some other header that should also be included in the calculations. I guess it would be good if someone with knowledge about the cbcl format could provide more information.

**Comment by nnordborg** [comment]
I have tried to extract the bytes from the "compressed block" from C1.1\L001_1.cbcl and C1.1\L001_2.cbcl using the 'dd' command and then de-compress it with 'gunzip'. Using the 34 bytes as specified in the header caused it to fail for the L001_1.cbcl file:
`$ dd if=L001_1.cbcl ibs=1 skip=65 count=34 | gunzip > /dev/null
34+0 records in
0+1 records out
34 bytes (34 B) copied, 4.0866e-05 s, 832 kB/s

gzip: stdin: unexpected end of file`

Changing to 35 bytes for L001_1.cbcl and 34 bytes for L001_2.cbcl seems to work:
`$ dd if=L001_1.cbcl ibs=1 skip=65 count=35 | gunzip > /dev/null
35+0 records in
0+1 records out
35 bytes (35 B) copied, 4.4715e-05 s, 783 kB/s

$ dd if=L001_2.cbcl ibs=1 skip=65 count=34 | gunzip > /dev/null
34+0 records in
0+1 records out
34 bytes (34 B) copied, 4.3446e-05 s, 783 kB/s`

So, my guess is that the header information in the 100-byte cbcl files is incorrect. Note that I have only checked a few of the cbcl files and I don't know if there are files with different size or different value for the compressed block size header.

**Comment by nnordborg** [comment]
I managed to add a simple test case that is using the existing data in the `testdata/picard/illumina/151T8B8B151T_cbcl` directory. I had to use READ_STRUCTURE=1S1T to get around the problem with incorrect value for the compressed block size in C1.1/L001_1.cbcl. In cycle 2 both cbcl files have correct headers. This is what I added to CheckIlluminaDirectoryTest:

```
private static final File CBCL_BASECALL_DIR = new File("testdata/picard/illumina/151T8B8B151T_cbcl/Data/Intensities/BaseCalls");

@Test
public void cbclWithSkipsInReadStructureTest()
{
    final int lane = 1;
    final IlluminaDataType[] dataTypes = new IlluminaDataType[]{BaseCalls};
    final String[] args = 
            makeCheckerArgs(CBCL_BASECALL_DIR, lane, "1S1T", dataTypes, new ArrayList<>(), false, false);
    Assert.assertEquals(runPicardCommandLine(args), 0);
}
```

What do you think? Is this enough?

**Comment by gbggrant** [comment]
Thanks @nnordborg having that test is better than none at all.  Maybe just put a comment in the test explaining what you found about the incorrect value in the test cbcl.

**Comment by gbggrant** [comment]
retest this please

**Pull request merged**
