### PR TITLE
Converted CollectQualityYieldMetrics to be a single pass SAM program …

### PR DESCRIPTION
**Pull request by tfenne**
…and tied it into CollectMultipleMetrics.

### CODE REVIEW

**Comment by tfenne** [comment]
@ktibbett @nh13 A simple change to convert CollectQualityYieldMetrics into a single pass sam program so that it can be run in CollectMultipleMetrics.  I was honestly somewhat shocked it wasn't one ready!  No change to outputs anywhere.

**Comment by kbergin** [comment]
@tfenne Code changes in the PR look good, but I'm not seeing any tests for QualityYieldMetrics. It's own unit test and an addition to CollectMultipleMetricsTest would be great!

**Comment by tfenne** [comment]
I agree it would be nice to have tests covering this.  However I'm not up for writing tests for this right now given the fairly minor structural change.  If the rule is going to be that changes must be accompanied by tests that cover all modified code even when there were no such tests before hand, I will close this PR and find a different solution.

**Comment by kbergin** [comment]
@tfenne If it's ok with you, I can write a test on a new branch and you could rebase your changes onto it after it's merged in, so that the new changes can be tested as well?

**Comment by tfenne** [comment]
Thanks Kylee - that's generous of you.  Sounds good to me!

**Comment by kbergin** [comment]
As long as the rebase passes then :+1: ! Thanks Tim!

**Comment by tfenne** [comment]
Have rebased. Got some strange test failures locally, but not the relevant test.  Fingers cross the travis tests pass.

**Comment by kbergin** [comment]
Travis seems to be happy!

**Pull request merged**
