### PR TITLE
Update java version requirement

### PR DESCRIPTION
**Pull request by vdauwera**
Addresses https://github.com/broadinstitute/picard/issues/359

### CODE REVIEW

**Comment by vdauwera** [comment]
@bih00425 @lbergelson Does this doc change satisfy the request?

**Comment by vdauwera** [comment]
Build failure is clearly unrelated to my teensy tiny readme change.

**Comment by ktibbett** [comment]
Build seems to have succeeded.

**Comment by vdauwera** [comment]
It failed on my first commit then succeeded on my second (which was just more text editing). Not used to Travis, bit temperamental?

**Comment by ktibbett** [comment]
occasionally....

**Comment by bih00425** [comment]
thanks

**Comment by lbergelson** [comment]
Ah, thanks @vdauwera.  I put that on my list of things to do and then just completely forgot about it.  Sorry for the wait @bih00425.

**Comment by vdauwera** [comment]
YW @lbergelson. 

FYI @dekling is working on rewriting some of the intro/quickstart docs on the picard docs website which are also grievously out of date.

**Pull request merged**
