### PR TITLE
adding cumulative plot to insert size

### PR DESCRIPTION
**Pull request by nh13**

### CODE REVIEW

**Comment by yfarjoun** [comment]
:+1:

**Comment by tfenne** [comment]
Very nice.  Can i suggest though that instead of having all the cumulative lines be black, that they be color-coordinated with the original series?  So if there is both a FR and RF distribution shown you can tell which is which by color for the cumulative?  Maybe just use "dark[color]"?

**Comment by tfenne** [comment]
Doh!  @yfarjoun merged while I was typing.

**Comment by yfarjoun** [comment]
should I revert?

**Comment by nh13** [comment]
@yfarjoun I will submit a patch.

**Comment by nh13** [comment]
https://github.com/broadinstitute/picard/pull/339

**Pull request merged**
