### PR TITLE
Small updates to the RQC metrics collector.

### PR DESCRIPTION
**Pull request by eitanbanks**
1. Ignore non-PF reads.
2. Add TOTAL_READS_ALIGNED to the metrics.

### CODE REVIEW

**Comment by ktibbett** [comment]
@eitanbanks  (recognizing fully that it is a little late in the game for this kind of comment), at least when adding new metrics can we try to use the same name we use for a metric in other places?  In this case, I think TOTAL_READS_ALIGNED should be PF_READS_ALIGNED.

**Comment by ktibbett** [comment]
Also, please consider whether other metrics names should be changed since they are now "PF" rather than "TOTAL."

**Comment by eitanbanks** [comment]
@ktibbett I've gone ahead and renamed all of the metrics that started with TOTAL_ to PF_ as requested.
Tests passing.  Okay to merge?

**Comment by yfarjoun** [comment]
don't you need a flyway script for this?

**Comment by ktibbett** [comment]
@eitanbanks , please wait until we make the database changes internally to merge.

**Comment by eitanbanks** [comment]
Roger that.
@yfarjoun flyways only needed for the uploader tools.

**Comment by eitanbanks** [comment]
Got verbal okay to merge from Kathleen.

**Pull request merged**
