### PR TITLE
chore: bump htsjdk to 3.0.3

### PR DESCRIPTION
**Pull request by clintval**
### Description

Bumping htsjdk to pull in recent changes bug fixes and enhancements.

Changes in htsjdk are here: https://github.com/samtools/htsjdk/compare/3.0.1...3.0.3

----

#### Content
- [ ] ~Added or modified tests to cover changes and any new functionality~
- [ ] ~Edited the README / documentation (if applicable)~
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by lbergelson** [comment]
@clintval Ooof... we broke compatibility with existing vcfs because they don't match the new enhanced sort order.  Bleh, I really should have foreseen that one.

**Comment by clintval** [comment]
@lbergelson I realized this too.

It seems there will be people using `VariantContextComparator` for "location only" comparison. Here's one:

https://github.com/fulcrumgenomics/fgbio/pull/884#discussion_r1024494844

I still think we made a good improvement, but should we be more clear with release note warning?

**Comment by lbergelson** [comment]
@clintval I agree that it was a good change, but I've rolled it back for now because of the way it's interacting with existing VCFs.  We validate that input vcfs match the expect sort order, so it broke cases where we are reading existing valid vcfs.  We have a similar issue with samfiles and fixed it by making 2 comparators, a validator and a sorter, so the validating one is looser and ignores tiebreakers and the like while reading input, and the full comparator is used when we're sorting output files..  We'll have to do something similar for VCFs.

**Comment by lbergelson** [comment]
Closing this.  3.0.4 is the newest now but it doensn't include the change we wanted in 3.0.3

**Pull request closed without merging**
