### PR TITLE
relaxing requirements for VCFIndex in tools that don't need one

### LINKED ISSUE #1111: RenameSampleInVcf requires VCF to be index before execution
### Affected tool(s)
RenameSampleInVcf

### Affected version(s)
- [X ] Latest public release version [2.17.8]

### Description 
I attempted to rename the sample in an unindexed single-sample VCF using RenameSampleInVcf. The message indicates an exception occurred due to the input file is not indexed.

````
java -jar ./picard-tools-2.17.8/picard.jar RenameSampleInVcf I="/scratch/lym_myl_rsch/mma/Green/sv_benchmark/Meerkat/BJAB/BJAB_C9FB2ANXX_s8_1_MRG_8bp_38_SL200962_trimmed.realigned.recalibrated.deduplicated.variants.sorted.filtered.vcf" O="/scratch/lym_myl_rsch/mma/Green/sv_benchmark/Meerkat/BJAB/BJAB_C9FB2ANXX_s8_1_MRG_8bp_38_SL200962_trimmed.realigned.recalibrated.deduplicated.variants.sorted.filtered.renamed.vcf" NEW_SAMPLE_NAME=BJAB
14:43:05.853 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/scratch/lym_myl_rsch/mma/picard-tools-2.17.8/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Feb 09 14:43:05 CST 2018] RenameSampleInVcf INPUT=/scratch/lym_myl_rsch/mma/Green/sv_benchmark/Meerkat/BJAB/BJAB_C9FB2ANXX_s8_1_MRG_8bp_38_SL200962_trimmed.realigned.recalibrated.deduplicated.variants.sorted.filtered.vcf OUTPUT=/scratch/lym_myl_rsch/mma/Green/sv_benchmark/Meerkat/BJAB/BJAB_C9FB2ANXX_s8_1_MRG_8bp_38_SL200962_trimmed.realigned.recalibrated.deduplicated.variants.sorted.filtered.renamed.vcf NEW_SAMPLE_NAME=BJAB    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Fri Feb 09 14:43:05 CST 2018] Executing as mma@cnode337 on Linux 2.6.32-431.23.3.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14; Deflater: Intel; Inflater: Intel; Picard version: 2.17.8-SNAPSHOT
[Fri Feb 09 14:43:05 CST 2018] picard.vcf.RenameSampleInVcf done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=504889344
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.tribble.TribbleException: An index is required, but none found., for input source: file:///scratch/lym_myl_rsch/mma/Green/sv_benchmark/Meerkat/BJAB/BJAB_C9FB2ANXX_s8_1_MRG_8bp_38_SL200962_trimmed.realigned.recalibrated.deduplicated.variants.sorted.filtered.vcf
        at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:134)
        at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:110)
        at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:74)
        at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:117)
        at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:68)
        at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:52)
        at picard.vcf.RenameSampleInVcf.doWork(RenameSampleInVcf.java:118)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:269)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)
````

#### Steps to reproduce
See the first line above for the command-line prompt I used. It's a standard operation without special arguments.

#### Expected behavior
If input is not indexed, it should be indexed before feeding it into `htsjdk.tribble.TribbleIndexedFeatureReader`.

#### Actual behavior
Exception occurred as the input has not been indexed.

### PR DESCRIPTION
**Pull request by lbergelson**
### Description

Fixes #1111. 

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by yfarjoun** [comment]
one of the two cases you fixed is already fixed in master (by you!).

Also a few more can be converted: 
picard/vcf/processor/VcfFileSegmentGenerator.java:108
picard/vcf/MendelianViolations/FindMendelianViolations.java:193

**Comment by yfarjoun** [comment]
@lbergelson do you want to move this PR along?

**Comment by yfarjoun** [comment]
@lbergelson is there a reason this isn't merged?

**Comment by yfarjoun** [comment]
bump

**Comment by lbergelson** [comment]
Oh.  I thought this WAS merged.

**Pull request merged**
