### PR TITLE
Only run PR build, not the branch build

### PR DESCRIPTION
**Pull request by jessicaway**
### Description

The PR build runs on the merge commit for a PR, while the branch build runs on the branch code. The branch build does not run for fork PRs, but the passing test is still required for merge. Since there is a branch protection in place requiring the PR to be up to date with the base branch, the tests are redundant. 

This PR skips branch tests whenever there is a corresponding PR. The tests will still appear, but they will not check out code or run. This PR also updates from Trusty to Xenial (as trusty was spontaneously broken) and removed te oraclejdk8 iteration of the tests (since xenial does not support oraclejdk8)
----

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by lbergelson** [comment]
This has the side effect of making it necessary to create a PR in order to trigger a build I believe. It will no longer be possible to push a branch and have it tested without making a PR.  That's a useful part of my workflow but I may be in the minority.

**Comment by lbergelson** [comment]
In GATK we short circuit the branch tests IFF there's an associated PR build.  It's not ideal.  If you can figure out a way to only run PR builds when there is a PR, but still run branch builds on non-pr branches that would be ideal.

We do it like this:
travis.yml
```
...

before_install:
  #skip push builds if there's an associated PR because we don't look at them anway
- if [[ ${TRAVIS_EVENT_TYPE} == push ]];
  then
    PULL_REQUESTS=$( scripts/travis/check_for_pull_request );
    if [[ $( grep -c "commits" <<< ${PULL_REQUESTS} ) -gt 0 ]];
    then
      travis_terminate 0;
    fi;
  fi;

...

```

scripts/travis/check_for_pull_request
```
#!/usr/bin/env bash

#query github for information about a specific pull request
curl -v -H "Authorization: token $GITHUB_API_TOKEN" https://api.github.com/repos/broadinstitute/gatk/pulls\?state\=open\&head="broadinstitute:${TRAVIS_BRANCH}"
```

**Comment by lbergelson** [comment]
What we do is super janky and can maybe be improved though.  Let us know if you figure out a good way!

**Comment by gbggrant** [comment]
You can still trigger a build by making a draft PR, which is how it's done in picard-private (which doesn't use Travis).  Not ideal.

**Review by nikellepetrillo — APPROVED** [review]

**Review by gbggrant — APPROVED** [review]

**Review by gbggrant — APPROVED** [review]

**Pull request merged**
