### PR TITLE
moving metrics tallying to a public static method, so it can be used by

### PR DESCRIPTION
**Pull request by nh13**
others (it is really useful).

@tfenne

### CODE REVIEW

**Comment by jacarey** [comment]
Would it make sense to pull BarcodeMetrics out to its own class so others can use that as well without the having to reference ExtractIlluminaBarcodes? It seems like if these are useful to others (not ExtractIlluminaBarcodes?) we should pull them up to the as to the top level.

**Comment by nh13** [comment]
@jacarey that makes a lot of sense, however, I want to make the simplest change to not cause disruption to others and make progress on my own work.  Your suggestion may break the Broad pipeline, which relies on class names, but you could confirm.   In light of these, I think this should be fine to merge.

**Comment by jacarey** [comment]
Agreed. I think this is fine for merge.

**Comment by nh13** [comment]
@jacarey I can't merge in this repo, would you do the honors?

**Pull request merged**
