### PR TITLE
Update README.md to show license badge

### PR DESCRIPTION
**Pull request by sooheelee**
Added '[License: MIT](https://github.com/broadinstitute/picard/blob/master/LICENSE.txt)' to top of README.md. Clicking on the badge will open the specific Picard repo's license.

### Description

_Give your PR a **concise** yet **descriptive** title_
_Please explain the changes you made here._
_Explain the **motivation** for making this change. What existing problem does the pull request solve?_
_Mention any issues fixed, addressed or otherwise related to this pull request, including issue numbers or hard links for issues in other repos._
_You can delete these instructions once you have written your PR description._

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [x] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by sooheelee** [comment]
I accidentally tabbed through the PR form section of the change to add the LICENSE.txt file and it committed directly to master. Sorry about that. For this change to the README, I'm practicing pull requesting.

**Comment by nh13** [comment]
@vdauwera can you make the master branch protected so only PRs can change it?  It should be in the settings for the repo.

**Comment by vdauwera** [comment]
Ah well, if you're not touching code it's not critical. Just make sure to learn from the experience, since it is considered rather bad form to commit directly to master.

**Comment by vdauwera** [comment]
And yes @nh13 I will do that

**Comment by sooheelee** [comment]
Yes, again sorry! I need to do these kinds of changes more regularly or change my tabbing habits.

**Comment by vdauwera** [comment]
Hmm I'm not seeing the settings -- I don't seem to be an admin here (cue sad sobbing). 

@jacarey @yfarjoun Do you guys have admin permissions? Please either protect master or make me an admin so I can do it. Pretty dangerous state of affairs otherwise.

**Pull request merged**
