### PR TITLE
update DownsampleSam doc to reflect required metrics file in example …

### PR DESCRIPTION
**Pull request by sooheelee**
…command and new piping in feature

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [x] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by nh13** [comment]
@sooheelee the metrics file is not required and can be omitted.  Also, I think having the "supports piping stdin" is really ugly in the command line argument.  My 2 cents.

**Comment by vdauwera** [comment]
Yeah, if it's not required I would prefer to have a note in the tool description stating that if you specify a metrics file, X happens, and pointing to the metrics arg, rather than including an optional arg in the example command. 

Also not a fan of the "supports piping stdin" note. I assume other tools support this and we've never made that sort of note for them -- it would be tiresome and clutter-prone to do so. Maybe what we need there is a short FAQ article or some such stating that some/many/most (select as appropriate) tools support piping read input, and providing some guidance for how to find out which, or noting exceptions, or whatever as applicable.

**Comment by yfarjoun** [comment]
seems like this change is undesired.

**Comment by kbergin** [comment]
To clean up this repo, we are deleting stale branches that have been merged or closed. You have a short period of time to restore this branch if needed. Thanks!

**Pull request closed without merging**
