### PR TITLE
replace git link with https link

### PR DESCRIPTION
**Pull request by etienneplatini**
Regular users can't clone the repository with the git link

### Description

_Give your PR a **concise** yet **descriptive** title_
_Please explain the changes you made here._
_Explain the **motivation** for making this change. What existing problem does the pull request solve?_
_Mention any issues fixed, addressed or otherwise related to this pull request, including issue numbers or hard links for issues in other repos._
_You can delete these instructions once you have written your PR description._

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by yfarjoun** [comment]
Not sure what you mean by "regular users". @vdauwera can you see what is needed here?

**Comment by vdauwera** [comment]
Oh yes -- if you're not on the repo team (I think that's the requirement) the git clone command given in the readme doesn't work. Using the https link as suggested in the patch fixes it. We should accept this change.

**Comment by yfarjoun** [comment]
should the readme have the git@ link as well?

**Comment by vdauwera** [comment]
Not sure what is the purpose of the git@ link since https works fine for all use cases that I'm aware of. If we can't justify why you'd want to use that one (and i sure can't) we shouldn't include it.

**Comment by yfarjoun** [comment]
I thought that only the ssh link works for cloning for the purpose of
making commits and pushing to github.

**Comment by yfarjoun** [comment]
👍

**Comment by yfarjoun** [comment]
nevermind. it works. I tested it.

**Pull request merged**
