### PR TITLE
Set compression level for GZIP files

### PR DESCRIPTION
**Pull request by nnordborg**
The COMPRESSION_LEVEL command line parameter is not used when writing GZIP files. This should fix this but requires that https://github.com/samtools/htsjdk/pull/159 is also merged into samtools.

### CODE REVIEW

**Comment by vdauwera** [comment]
@nnordborg Are you still working on this? It looks like the build failed last time it was run. If this is not ready for review, please close the pull request until it is.

**Comment by nnordborg** [comment]
We deployed it in our server environment. It works but seems like it didn't made as much difference as some was hoping for. You'll need the samtools fix also before Picard will build.

**Comment by nh13** [comment]
@nnordborg can you point us to the 'samtools fix'?

**Comment by vdauwera** [comment]
I believe he means samtools/htsjdk#159 as mentioned in the OP.

**Comment by nh13** [comment]
We are tracking the htsjdk changes here: https://github.com/samtools/htsjdk/pull/271

**Comment by vdauwera** [comment]
samtools/htsjdk#271 was merged. Is there anything that needs to be done here or can this be closed?

**Comment by vdauwera** [comment]
No activity in over a year; closing.

**Pull request closed without merging**
