### PR TITLE
Adds support for reading CSI indexes.

### PR DESCRIPTION
**Pull request by valeriuo**
### Description

Handles the CSI indexes implemented in [HTSJDK](https://github.com/samtools/htsjdk/pull/1040). More specifically, it uses the new type, `BAM_CSI_TYPE`.

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [x] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [x] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by gbggrant** [comment]
retest this please

**Comment by valeriuo** [comment]
@gbggrant if you are referring to the failed Travis build, the symbol [SamReader.Type.BAM_CSI_TYPE](https://github.com/valeriuo/htsjdk/blob/b16a421bc6846d17841cb97e1f34861bae314552/src/main/java/htsjdk/samtools/SamReader.java#L88) is defined in the [htsjdk PR 1040](https://github.com/samtools/htsjdk/pull/1040), which is still under review. So, I am assuming we'll need to wait for that PR to be merged in order to rebuild this branch.
In the meantime, if there are other tests you need me to perform with my own version of htsjdk, which contains the missing symbol, please let me know.

**Comment by magicDGS** [comment]
@valeriuo - you can use a htsjdk snapshot from your PR (if I am correct) from the [Broad artifactory](https://broadinstitute.jfrog.io/broadinstitute/webapp/#/home), which is included in Picard.

Like that, you can test that it is working and hold the merge until a released version with your fix is in.

**Comment by yfarjoun** [comment]
the dependent PR was merged into master and released in htsjdk 2.19.0, so if you rebase this PR on picard/master the tests should pass.

**Comment by FredericBGA** [comment]
Hi, 
What is missing for this PR to be merged? Can I help?
We are really interested in this new feature, so I am interested if I can do something.

**Comment by valeriuo** [comment]
I will have another look at this. The rebase went smoothly, but it probably needs a few changes, as I see some stuff has been deprecated in the meantime.

**Comment by yfarjoun** [comment]
@gbggrant it seems that the PR has been updated in response to your comments would you be able to take another look and move it along?

**Review by gbggrant — APPROVED** [review]
Looks good.

**Pull request merged**
