### PR TITLE
issue #183 - Changes to accommodate v1.5 of the SAM file specification.

### PR DESCRIPTION
**Pull request by nenewell**
The version number fields of test files, including text format, .bam, and .cram files, are updated to accommodate the change to v1.5 of the SAM file specification.  These changes depend on pull request https://github.com/samtools/htsjdk/pull/233 - the changes to htsjdk for the same purpose.

### CODE REVIEW

**Comment by nenewell** [comment]
I think this failed Travis checks because the htsjdk changes are not yet merged.

**Comment by nh13** [comment]
Relevant htsjdk pull request: https://github.com/samtools/htsjdk/pull/285

**Comment by nh13** [comment]
Verified that unit tests pass when htsjdk is updated.

**Comment by nh13** [comment]
Fixed the build here: https://github.com/broadinstitute/picard/pull/240

**Pull request closed without merging**
