### PR TITLE
Adding a new tool ReplaceVcfHeader.

### PR DESCRIPTION
**Pull request by nh13**
@tfenne @yfarjoun testing the appetite for this tool.  I will add tests if folks 👍.

### CODE REVIEW

**Comment by vdauwera** [comment]
This is a great start but I'd love to see an option to automatically generate a new header (instead of replacing with a hand written one) where missing header lines have been added on the fly. Possibly even with an option to provide a description string for missing fields on the command line, to populate the lines of the added field definitions. Does that make sense? I can provide a worked out example if it helps.

**Comment by nh13** [comment]
@vdauwera that is a lot more effort than this tool (see the analogous `ReplaceSamHeader` tool). It is also difficult to know the various fields to insert for the info/format fields (type, number, description, source, version).   I agree a tool that could do this automatically more useful to the user, but this better than nothing, and the desire for the former should not remove the appetite for the latter.

**Comment by vdauwera** [comment]
That's fair -- just putting the idea out there (as the French lottery slogan goes, 100% of winners tried their luck). But I agree that if this is as far as you want to go for now, it is still very worthwhile and we should take it in.

**Comment by nh13** [comment]
@yfarjoun not sure if I would have this tool separate from `FixVcfHeader` in https://github.com/broadinstitute/picard/pull/530.  I could keep both tools but remove the replace header functionality from `FixVcfHeader` or close this PR.  Either way is fine by me.

**Comment by yfarjoun** [comment]
without this PR, you will not be able to replace a header as is, since
FixVcfHeader will fix the new header...I'd advocate leaving both.

**Comment by yfarjoun** [comment]
Thinking about this more, I think that a single tools with optional HEADER and boolean FIX_HEADER and boolean REQUIRE_SAME_SAMPLES would be ideal. 

that single tools together with some test cases would get a 💯  from me. 😄

**Comment by nh13** [comment]
Closing this in favor of https://github.com/broadinstitute/picard/pull/530.

**Pull request closed without merging**
