### PR TITLE
fixing histogram count bug in mark illumina adapters

### PR DESCRIPTION
**Pull request by nh13**

### CODE REVIEW

**Comment by nh13** [comment]
The histogram counts were being updated based on the first record of a pair, which is problematic when the second record is clipped at a different offset/index.

**Comment by akiezun** [comment]
i have 1 comment: this needs a regression test

**Comment by nh13** [comment]
I don't see any existing regression tests for "MarkIlluminaAdapters" to which to update; also is a bug fix not a new feature.  Thanks for reviewing.

**Comment by akiezun** [comment]
bug fixes need regression tests

**Comment by nh13** [comment]
closing as there are no tests.

**Comment by yfarjoun** [comment]
hey boys. can we please stop this.

**Comment by yfarjoun** [comment]
@nh13 Thank you very much for spotting this bug, and suggesting a fix. Would you be able to supply two reads that cause an error so that **we** could write a test for this? That would be very much appreciated!

**Comment by nh13** [comment]
Moving this to https://github.com/broadinstitute/picard/pull/341.

**Pull request closed without merging**
