### PR TITLE
Fix bug in CollectSamErrorMetrics

### PR DESCRIPTION
**Pull request by mollysacks**
### Description

Fixes a few issues with CollectSamErrorMetrics

1. CollectSamErrorMetrics was not checking if bases had base quality/ mapping quality above user specified threshold before including them in error bases. Thus, bases were included in ERROR_BASES but not included in TOTAL_BASES, resulting in incorrect (and sometimes negative) Q scores. To fix this bug, we added an if statement in CollectSamErrorMetrics that checks if the record meets the user specified thresholds before adding it to any aggregator.
2. CollectSamErrorMetrics was counting indels as error bases when collecting `ERROR:${STRATIFIER}` error metrics (as opposed to `INDEL_ERROR:${STRATIFIER}` or `OVERLAPPING_ERROR:${STRATIFIER}`). This can cause error bases to be greater than total bases for strata that contain more indels than total bases. Thus, we decided to not include indels in this metric.

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [x] Added or modified tests to cover changes and any new functionality
- [x] Edited the README / documentation (if applicable)
- [x] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by gbggrant** [comment]
@mollysacks is this PR ready for review?  If so, please move it out of draft status.

**Comment by tmelman** [comment]
@mollysacks looks good, did you only have one testcase file with indels? what other tests did you do?

**Comment by mollysacks** [comment]
> @mollysacks looks good, did you only have one testcase file with indels? what other tests did you do?

So far I only have one test case, if you think I should add another one I can! Should be pretty simple

**Review by tmelman — APPROVED** [review]
👍

**Pull request merged**
