### PR TITLE
Issue #769: Correct the quality score to be reported to HistogramArray.

### PR DESCRIPTION
**Pull request by renkyp**
### Description

Issue #769, modify the quality score to be used. 

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by yfarjoun** [comment]
This looks good. I also fixed this in a separate PR  #771. I'm happy to let you have the honor of authoring the fix, but my PR also has a test 😄 

Would you like to copy over the test and add it to your branch, or should we proceed with my branch?

**Comment by renkyp** [comment]
@yfarjoun  Seems that the test went wrong somehow...

**Comment by yfarjoun** [comment]
look again. I just pushed the test before the fix, so that we see that the fix fixes the test.

**Comment by renkyp** [comment]
@yfarjoun  Alright, Let's go with your PR. :)

**Comment by yfarjoun** [comment]
closed in favor of #771

**Pull request closed without merging**
