### PR TITLE
Added 1 pct_bases_1x to CollectWgsMetrcics' output.

### PR DESCRIPTION
**Pull request by tfenne**

### CODE REVIEW

**Comment by tfenne** [comment]
@ktibbett a fairly trivial change to just add pct_1x to the metrics output.  I realize that this is computable from the histogram in the file, but it's convenient to have it defined in the regular metrics so that you can compute 1x and 0x coverage without resorting to dealing with the histogram.

**Comment by yfarjoun** [comment]
the travis build is failing....due to java 1.8 in htsjdk, I think....

**Comment by tfenne** [comment]
@yfarjoun rebased on top of master now that the java 8 problem is fixed.  Ok to merge?

**Comment by yfarjoun** [comment]
@ktibbett please chime in here...will this do something bad to the "UploadMetrics" without a matching DB change?

**Comment by ktibbett** [comment]
@yfarjoun , yes it will break things.  I've made a ticket to the change on our end; it's small and I'll merge this as soon as that's complete.  OK, @tfenne ?  (Hoping for tomorrow.)

**Comment by tfenne** [comment]
Thanks @ktibbett

**Comment by nh13** [comment]
@ktibbett add metric columns shouldn't break things, it just wont be tracked in the db, or have things changed?

**Comment by mattsooknah** [comment]
@nh13 it will break the uploader in picard-private, since we currently use reflection on the metric fields to prepare the insert statement. So you'd get errors like this:

```
Exception in thread "main" picard.PicardException: executing MetricInserter{bean=class edu.mit.broad.picard.aggregation.UploadAggregationMetrics$Metrics$ForeignKeyFauxMetric,class picard.analysis.CollectWgsMetrics$WgsMetrics, statementString='insert into AGGREGATION_WGS (AGGREGATION_ID, GENOME_TERRITORY, MEAN_COVERAGE, SD_COVERAGE, MEDIAN_COVERAGE, MAD_COVERAGE, PCT_EXC_MAPQ, PCT_EXC_DUPE, PCT_EXC_UNPAIRED, PCT_EXC_BASEQ, PCT_EXC_OVERLAP, PCT_EXC_CAPPED, PCT_EXC_TOTAL, PCT_1X, PCT_5X, PCT_10X, PCT_15X, PCT_20X, PCT_25X, PCT_30X, PCT_40X, PCT_50X, PCT_60X, PCT_70X, PCT_80X, PCT_90X, PCT_100X) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'}
	...
Caused by: java.sql.BatchUpdateException: ORA-00904: "PCT_1X": invalid identifier
	at oracle.jdbc.driver.DatabaseError.throwBatchUpdateException(DatabaseError.java:343)
	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:10656)
	at edu.mit.broad.picard.db.MetricsUploader$MetricInserter.executeInsert(MetricsUploader.java:362)
	at edu.mit.broad.picard.db.MetricsUploader.doInserts(MetricsUploader.java:133)
	... 6 more
```

**Comment by kbergin** [comment]
I've written a flyway script and test file for this new metric but matt pointed out the tests won't pass on jenkins until this branch gets merged in. My local tests with this branch and my branch pass so I believe this PR can be merged and then we can merge mine. :+1:

**Comment by tfenne** [comment]
Thanks @kbergin .  Merging now!

**Pull request merged**
