### PR TITLE
Cleanup - pmd:UseIndexOfChar - Use Index Of Char

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule pmd:UseIndexOfChar - Use Index Of Char

You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:UseIndexOfChar

Please let me know if you have any questions.

M-Ezzat

### CODE REVIEW

**Comment by nh13** [comment]
@m-ezzat can you show the performance difference of this change for these two classes?

**Comment by m-ezzat** [comment]
I don't think that it makes that performance change in these a few number of lines! but, I've targeted the code to be clean, and it will be a principle to be followed.

**Comment by yfarjoun** [comment]
@m-ezzat, Thank-you for your interest in the Picard project! It is clear
that you intend to help make this (and many other) project better with your
contributions.

However, you must be aware that reviewing PRs takes effort on the part of
the rest of the community. Your contributions would be better received and
more readily reviewed if they can be seen as actual improvements, i.e.
bug-fixes, new features, performance improvements.

If your contributions' only achievements is to make the code adhere to a
seemingly endless list of SQUID- rules, with no additional improvement in
the code, you run the risk of creating antagonism rather than appreciation
for your contribution, as you are continuously "violating" the maxim "If it
ain't broke, don't fix it"...

Perhaps a better way to enforce these rules would be applying them to other
people's pull requests and commenting when they "violate" them...That way
it will not require much extra effort on the part of the community and it
will help improve the code.

**Comment by m-ezzat** [comment]
@yfarjoun Ok, got it

**Comment by yfarjoun** [comment]
👍 This code is fine.

**Pull request merged**
