### PR TITLE
fixed a small bug in IntervalListTool and remove spurious exception

### PR DESCRIPTION
**Pull request by yfarjoun**
- Fixed a small bug in IntervalListTool where in some cases bases were not accounted for in the total count (this can lead to non-uniform intervalLists in the scatter)

- Removed an erroneous Exception that was thrown when the intervals were not uniformly enough sized. We cannot guarantee that they will be uniformly sized...

- Fixed bug that was causing the Last intervalList to be double the size of the rest.

### CODE REVIEW

**Comment by ktibbett** [comment]
image

**Comment by yfarjoun** [comment]
Note: the last interval generated here might still be too big. This needs a careful look.

**Comment by yfarjoun** [comment]
@ktibbett found -1 bug we discussed yesterday. Please re-review.
@nh13 you might enjoy this one too.

**Comment by nh13** [comment]
:+1:

**Pull request merged**
