### PR TITLE
Revert "Yf use mapped file dictionary v2"

### PR DESCRIPTION
**Pull request by nh13**
Reverts broadinstitute/picard#682

See issue: https://github.com/broadinstitute/picard/issues/734

Since *a lot* of folks use this capability, I think the commit should be reverted.

### CODE REVIEW

**Comment by tfenne** [comment]
I agree this should be reverted temporarily, but don't want to hit the merge button without giving @yfarjoun a chance to comment.

**Comment by nh13** [comment]
@yfarjoun bump?

**Comment by tfenne** [comment]
I think @yfarjoun opened his own PR here #737

**Comment by yfarjoun** [comment]
yes. sorry, we were working in parallel and I already merged my revert.

I also already fixed the code and am now struggling with how to test...any
ideas or examples are welcome...

**Pull request closed without merging**
