### PR TITLE
Fixing previous mistake with scheme logic

### PR DESCRIPTION
**Pull request by kbergin**
I had a mistake in the scheme logic in the last pull request where I had set most of the MISSING truth states to call like NO_CALLS, when in fact they should be called identical to HOM_REF. This pull request fixes that scheme logic, and the corresponding tests.

### CODE REVIEW

**Comment by kbergin** [comment]
@nh13 I made this new PR to fix the scheme settings in #229. I changed the MISSING column and the hard coded test comparisons in the corresponding tests. If you get a chance, could you :+1: if it looks good?

**Comment by yfarjoun** [comment]
did you calculate the test results by hand?

**Comment by kbergin** [comment]
Yes I did. I did last time as well but I calculated them off of a scheme that wasn't valid so they still came out as correct then.

**Comment by yfarjoun** [comment]
just checking! :-)

**Comment by kbergin** [comment]
Thanks!!

**Comment by nh13** [comment]
:+1:

**Comment by kbergin** [comment]
Thanks!

**Pull request merged**
