### PR TITLE
Making more classes and methods public in Genotype Concordance.

### PR DESCRIPTION
**Pull request by nh13**
Also fixed a NPE when run on a whole genome (no intervals).

### CODE REVIEW

**Comment by nh13** [comment]
@eitanbanks exposed a few more methods.  For context, this should allow other tools to easily compute the same metrics as `GenotypeConcordance`, or compute the concordance state of individual variants.

**Comment by nh13** [comment]
One more commit coming right up

**Comment by nh13** [comment]
Should be all set, I wont touch this, and will make another PR if I find anything else that needs to be exposed.

**Comment by eitanbanks** [comment]
Yes, looks good.  Need me to merge it for you?

**Comment by nh13** [comment]
Yes please. I don't have merge privileges.

**Pull request merged**
