### PR TITLE
trying to fix the intellij setting so that it points to the 1.8 java sdk

### PR DESCRIPTION
**Pull request by yfarjoun**
@ktibbett, we talked about this a while back. Can you take a look?

### CODE REVIEW

**Comment by lbergelson** [comment]
@yfarjoun We'd be better off deleting the project files than trying to keep them up to date I think.  Everyone in the world has their own unique IDE settings and committing project files means everyone has to fight with the committed ones.

**Comment by yfarjoun** [comment]
hmmm. the point of having this is to help people have a good initial setup
of the project that "works" or very nearly works. I suspect that it is
helpful for folks who are just starting with picard. I know that setting up
GATK (which doesn't have intelliJ settings) is a royal pain if you do not
have someone telling you what to do...so I'm inclined to leaving these
around.

I'm happy to fix them every now and again when they break.

**Comment by tfenne** [comment]
I think the ideal situation is to, eventually, move over to a build system that provides better IDE integration.  My experience with projects that use either _gradle_ or _sbt_ has been that importing into IntelliJ does 99% of the configuration I need and want.  And then the build file(s) live in git, but the IntelliJ files don't because they can be auto-generated easily.

**Comment by akiezun** [comment]
+1 for gradle

**Comment by tfenne** [comment]
Just to be contrarian - the more I use sbt, the more I like it :smile:

**Comment by yfarjoun** [comment]
I have absolutely no problem with an alternative system that makes it easy
to start developing. until then, I think that the intelliJ files should be
included.

**Comment by cwhelan** [comment]
Another option is to provide an build target that generates IntelliJ files.
For example in Gradle the idea plugin can do this:

https://docs.gradle.org/current/userguide/idea_plugin.html

Customizing the task in the build file lets you fix any things that IDEA's
imports don't get 100% correct, if you keep it up to date. I worked on a
project before where this seemed to work well.

**Comment by ktibbett** [comment]
:+1: as the interim solution

**Pull request merged**
