### PR TITLE
Add AppSec GitHub Trivy Action

### PR DESCRIPTION
**Pull request by dinvlad**
### Description

The Docker image for Picard is used by some regulated production pipelines, including by the Broad Genomics Platform. Hence, it would be a good practice to subject it to the same compliance requirements.

As such, the DSP AppSec team would like to add our Docker image security scanner (Trivy) as a GitHub Action that will run on every PR. It will detect _Critical_ OS-level vulnerabilities (if any) in the image, and report it to you. You can then either:

* fix the issue (usually just by updating the packages in the Dockerfile), or
* ignore it, and document the reason with AppSec. Our compliance process has a timeline of 14 days for patching Critical vulnerabilities, or documenting why they are ignored.

Generally, after we sort out the results from the initial scan (if any), it should not return many positives, so this is a low-noise addition to your workflow. Generally (perhaps once a quarter) it can return 1-2 results, and it should be easy to fix those by updating the underlying base image and/or packages. The scanner only detects OS packages like Debian apt packages, and not Java packages (which are detected by another external tool), and we only report those that have a known fix.

As an alternative, you can adopt one of our recommended base images (https://github.com/broadinstitute/dsp-appsec-blessed-images), which are regularly scanned and patched for vulnerabilities. In that case, this GitHub Action will skip the scan so you won't have to worry about any findings at all.

Thanks!

More info:
https://github.com/broadinstitute/dsp-appsec-trivy-action
https://github.com/broadinstitute/dsp-appsec-blessed-images

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Review by jessicaway — APPROVED** [review]
Looks good to me

**Comment by gbggrant** [comment]
Note that under normal usage (from the build_push_docker.sh script) we use the build_command cloudjar, which is slightly different in packaging than shadowJar.  But I don't think that this would cause any differences in trivvy's findings.

**Comment by gbggrant** [comment]
@dinvlad looks good.  One minor comment about the usage of that Dockerfile - otherwise OK to merge.

**Comment by dinvlad** [comment]
Yea sounds good! If everything else but the JAR packaging is the same, then no differences indeed

**Comment by kbergin** [comment]
@dinvlad / all - can this PR be merged?

**Comment by dinvlad** [comment]
@kbergin yes please, I've just merged `master` branch!

**Comment by kbergin** [comment]
Great! @dinvlad if you have the permissions you can merge it! If not I'll have Jess or George do it tomorrow.

**Pull request merged**
