### PR TITLE
Cluster Visualization Python Script

### PR DESCRIPTION
**Pull request by mollysacks**
### Description

1. Python script that generates a visual representation of ClusterCrosscheckMetrics output. Instructions on how to run are in a comment at the top of the script

2. Python script that uses UMAP to generate a visual representation of the matrix output from CrosscheckFingerprints. 

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [x] Added or modified tests to cover changes and any new functionality
- [x] Edited the README / documentation (if applicable)
- [x] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by gbggrant** [comment]
Hi @mollysacks is this still a draft?  @kachulis was interested in having this merged.

**Comment by tmelman** [comment]
> Hi @mollysacks is this still a draft? @kachulis was interested in having this merged.

@gbggrant Molly Sacks's internship has ended. I can look this over.

**Comment by gbggrant** [comment]
@tmelman can you take a look at this PR? If it's not relevant, maybe it should be closed.

**Review by tmelman — APPROVED** [review]
Okay to merge.

**Comment by tmelman** [comment]
@gbggrant ok to merge this?

**Pull request merged**
