### PR TITLE
Update htsjdk 2.23.0 -> 2.24.0

### PR DESCRIPTION
**Pull request by lbergelson**
### Description

Updating htsjdk from 2.23.0 -> 2.24.0.

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Review by droazen — APPROVED** [review]
:+1: Looks good!

**Comment by droazen** [comment]
@sahakiann @snovod We'd love to see a Picard release with this updated version of HTSJDK go out this week, if it's at all possible. We're doing a major new release of GATK (https://github.com/broadinstitute/gatk) this week, which includes Picard as a dependency, and were hoping that we could ship with updated versions of both Picard and HTSJDK. This new HTSJDK release is the first release in over half a year and comes with a number of important fixes.

**Comment by sahakiann** [comment]
@droazen I can release today!

**Comment by sahakiann** [comment]
@droazen @lbergelson  Could you give me a heads up once this is merged and I can start the release?

**Comment by lbergelson** [comment]
Yay!

**Comment by lbergelson** [comment]
@sahakiann Thank you, I merged it just now.

**Comment by droazen** [comment]
@sahakiann Thanks for the quick action on this, much appreciated!

**Comment by sahakiann** [comment]
@lbergelson thanks! 
@droazen  no problem! Going to start with the release, should be done within an hour or so

**Comment by lbergelson** [comment]
@sahakiann Thanks for the super fast turn around.

**Comment by sahakiann** [comment]
@lbergelson  @droazen  you're welcome! Release is here: https://github.com/broadinstitute/picard/releases

**Pull request merged**
