### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yfarjoun**
provide instructions on simple cloning and building the package

@mattsooknah

### CODE REVIEW

**Comment by nh13** [comment]
This is confusing, since we have instructions here:
http://broadinstitute.github.io/picard/

**Comment by yfarjoun** [comment]
yes...I'm not sure what is more confusing...that the instructions in the
readme.md file talk about how to build ga4gh stuff and not picard, or that
the page you pointed at has instructions that do not actually work (need
some "cd" commands and "ant" commands to complete)

At any rate, I agree that the io page should be linked to from the readme,
and that it should be made more detailed....

**Comment by vdauwera** [comment]
The github readme will be read mostly by dev-savvy people and should feature the build instructions front and center. The .io site should emphasize that you can download the precompiled package because it is more targeted at end-users who are not interested in the source code.

**Comment by lbergelson** [comment]
I support this.  It's really annoying that you have had to go to a confusing external link to get the build instructions and then they're incomplete.

**Comment by nh13** [comment]
Can I then ask that the github pages branch is updated to make the instructions complete?

**Comment by vdauwera** [comment]
Sure.

**Comment by mattsooknah** [comment]
:+1:

**Pull request merged**
