### PR TITLE
Add missing tools to build.xml file so they get documented

### PR DESCRIPTION
**Pull request by dekling**
The build.xml page has been modified and now contains a comprehensive list of the Picard tools.  

However, there are six additional doc changes that ended up in this PR that I was planning on saving for a different PR.  That was unintentional, as I could not figure out how to select specific changes prior to rebasing against the master.

### CODE REVIEW

**Comment by vdauwera** [comment]
I can do it for you now and show you how it's done when I'm back in the office next week.

**Comment by dekling** [comment]
Great.  Thanks!

> On Feb 12, 2016, at 12:48 PM, Geraldine Van der Auwera <notifications@github.com> wrote:
> 
> I can do it for you now and show you how it's done when I'm back in the office next week.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/broadinstitute/picard/pull/436#issuecomment-183427528>.
> 

—
David E. Kling, Ph.D.
Senior Technical Writer
Broad Institute
75 Ames Street, #7003DC
Cambridge, MA 02142
O (617) 714 - 7351
C (617) 291 - 1617

**Comment by vdauwera** [comment]
Done. When tests pass this can be merged, right @yfarjoun?

FYI IntelliJ decided all on its own to fix the whitespace formatting on some parts of the file but I assume that's fine.

**Comment by yfarjoun** [comment]
:+1:

**Pull request merged**
