### PR TITLE
GTF and RefFlat to GenePred tool

### PR DESCRIPTION
**Pull request by PolinaBevad**
### Description 
As said in these issues, there was no GTF format as well as GenePred format support:
[GTF to Refflat tool for use with CollectRnaSeqMetrics](https://github.com/broadinstitute/picard/issues/805)
and [Tolerate GenePred input format in addition to refFlat](https://github.com/broadinstitute/picard/issues/926).

### Implementation
Our implementation involves adding several new classes, changing metrics according to logic of new entities, deleting one class which becomes unnecessary due to new logic and adding new test.
New entities:

- `RefFlatRecord`, `GTFRecord` and `GenePredRecord` which represent one record of each format respectively;
- `Converter` which converts GTFRecords and RefFlatRecords to GenePredRecords using streams;
`Reader` (interface) which returns stream of records from file;
- `Feature` (enum) describes possible types of Feature field of GTF file record.

Changed entities:
- `GeneOverlapDetectorLoader` (ex. `GeneAnnotationReader`) which produces genes from received GenePredRecords;
- `CollectRnaSeqMetrics` was changed according to new logic of `GeneOverlapDetectorLoader`.

Deleted entity:
- `RefFlatReader` which is now replaced with the universal `Converter`.

Tests:
- `ConverterTest` added;
- `CollectRnaSeqMetricsTest` changed (metrics based on GTF and RefFlat files added).
## Performance
We measured performance with JMH Benchmark for both cases (GTF to GenePred and RefFlat to GenePred convertations).
Benchmarks of `GeneOverlapDetectorLoader` with methods `gtfToGenePred()` and `refflatToGenePred()`:

Benchmark | Cnt | Units
-- | -- | --
CollectRnaSeqMetricsBenchmark.withGtfAsInput | 50 | 0.284 ± 0.009  ops/s
CollectRnaSeqMetricsBenchmark.withRefFlatAsInput | 50 | 2.356 ± 0.151  ops/s

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [X] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by nh13** [comment]
@PolinaBevad thank-you for taking a shot at this.  In addition to whomever @yfarjoun decides, I'd like to take a look at this.  I am out on vacation for a week or so, so hopefully you can wait until I am back for my review?

**Comment by yfarjoun** [comment]
take it!

**Comment by lbergelson** [comment]
@jonn-smith Just recently added a tribble codec to GATK for Gencode GTF files as well as a bunch of code to work with them, take a look at https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/utils/codecs/GENCODE/GencodeGtfFeature.java and related files.  

I'm not sure if that does exactly what you want here, but we might want to consider moving it to htsjdk instead of implementing a separate gtf reader in picard

**Comment by yfarjoun** [comment]
@nh13 bump?

**Comment by nh13** [comment]
@yfarjoun definitely on my list, I am hoping the holidays will afford more of an opportunity.  Who knew fires occur in December? ;)

**Comment by yfarjoun** [comment]
how will we stay warm otherwise?

**Comment by yfarjoun** [comment]
@lbergelson  could you work with @jonn-smith to move the relevant code form gatk into htsjdk? 

@PolinaBevad when that work is done, would you mind rebasing on top of that and using that code instead?

Closing since large changes seem to be required.

**Comment by jonn-smith** [comment]
We can probably pull the Gencode tribble codec from GATK into htsjdk.  This is lower priority than getting `Funcotator` out of beta, so I won't be able to help until the end of June at the earliest.

**Pull request closed without merging**
