### PR TITLE
Added check for REFERENCE_SEQUENCE to avoid NPE in CollectSequencingA…

### PR DESCRIPTION
**Pull request by tfenne**
…rtifactMetrics

### CODE REVIEW

**Comment by tfenne** [comment]
@yfarjoun This has been driving me crazy!  Because it inherits REFERENCE_SEQUENCE from a parent class, and it's optional up there, CSA doesn't give an error message if it's null, it just NPEs.  Trivial change to add a check for it and produce a nicer error message.

**Comment by yfarjoun** [comment]
👍

**Comment by nh13** [comment]
@yfarjoun I think I was assigned this in error.

**Comment by yfarjoun** [comment]
Oops. Thanks.

**Pull request merged**
