### PR TITLE
Added some totally alpha code for comparing sequence data to fingerpr…

### PR DESCRIPTION
**Pull request by eitanbanks**
…ints and cross checking it.

Do NOT use yet unless you know what you are doing and do not care about your results.
UNSUPPORTED (for now).  Do not ask for help (yet).

### CODE REVIEW

**Comment by eitanbanks** [comment]
@ktibbett I'm hoping that since it's labeled as alpha (and you've seen this code before) it might be a quick review...
I'm going to add some issues in github for future improvements.

**Comment by tfenne** [comment]
@eitanbanks just a couple of thoughts from me:
1. I could have sword there were also some tests for at least the core math and the metadata file format
2. I was kinda hoping some of the cross-checking and related tools would be coming along too .. any chance of that?
3. When this does get merged, it would be nice to add a bit more context to the comment, that this is code that has been used for a long time, but is considered alpha as there is a plan to modify it significantly after it's transfer into Picard.

**Comment by eitanbanks** [comment]
Yeah, sorry.  Just realized tests were not added in git.  Fixed.
The crosscheck code was included - it's in there.
Sure - I'll fix up the commit in a future rebase.

**Comment by eitanbanks** [comment]
@tfenne I fixed up the commit message

**Comment by ktibbett** [comment]
I am ok with merging this once tests tie out.

**Comment by yfarjoun** [comment]
oh this is so sweet!!

**Comment by vdauwera** [comment]
:tada:

**Comment by vdauwera** [comment]
Also when the tools are considered mature, be sure to add them to build.xml doc generation ant target because of https://github.com/broadinstitute/picard/issues/290

**Pull request merged**
