### PR TITLE
Adding a page to help explain and transform Base Qualities.

### PR DESCRIPTION
**Pull request by nh13**
I have found this useful when I want to convert between ASCII and integer-values for base qualities.

### CODE REVIEW

**Comment by tfenne** [comment]
Seems reasonable to me @nh13.  A little hard to tell without seeing it live on the site.

**Comment by vdauwera** [comment]
Will take a look later today and copy it to my fork of gh-pages so we can see what it looks like live.

**Comment by nh13** [comment]
@vdauwera that would be great to see!

**Comment by vdauwera** [comment]
See here: http://vdauwera.github.io/picard/explain-qualities.html

I think the layout could be improved to make it more user-friendly. And maybe add some brief instructions.

**Comment by nh13** [comment]
@vdauwera any suggestions on the layout and instructions, or want to submit a PR to this branch?  I am not an expert on UI.

**Comment by vdauwera** [comment]
I'll take a stab at it.

**Comment by nh13** [comment]
I am in your debt.

**Comment by vdauwera** [comment]
Working on it now, sorry it took a while

**Comment by vdauwera** [comment]
@nh13 Have a look at http://vdauwera.github.io/picard/explain-qualities.html

Do we maybe want to increase the size of the input field to allow for longer strings/reads? Could use a wrapped text box.

**Comment by nh13** [comment]
@vdauwera looking good!  I would say having the text field be at least 150 characters long (typical runs are 100-200 at the least) would be great.  I agree that a text area or a wrapped text box would be better.  If you make that change and squash into two commits (one for me, one for you), we could probably merge.

**Comment by vdauwera** [comment]
OK, done. Added text area and also set the word break property of the result paragraph to break-all to make sure the result/output wraps nicely. I think this is good to go.

**Pull request merged**
