### PR TITLE
Fix bug that causes CollectHsMetrics (and friends) to double-count...

### PR DESCRIPTION
**Pull request by tfenne**
…0-coverage sites in 0-coverage targets.

### CODE REVIEW

**Comment by tfenne** [comment]
Calling @yfarjoun, @kbergin and @davidbenjamin (and maybe @ktibbett).  It looks like when the theoretical het sensitivity code went in a bug got introduced that double-counted 0-coverage bases from 0-coverage targets when calculating the coverage distribution which is used for both the histogram in the metrics file _and_ the het sensitivity calculations.

Looking at it fresh, I think actually the `calculateTargetCoverageMetrics()` method is very confusing and error-prone.  It essentially calculates three different coverage distributions/arrays in parallel with a bunch of subtly different conditionals.   I'm positive it would be better long term to refactor to either calculate a single array from which all the resulting things are derived, or separate the array calculations so they are not interleaved with one another, and thus easier to follow.

If you look at the _before_ code you can see that on line 624 the distribution was being incremented for zero coverage targets.  And then on line 630 it was being incremented for _all_ bases regardless of whether the target has coverage or not.  

The result is that:
1. The zero coverage bin is not the same fraction of bases as `1-PCT_TARGET_BASES_1X` (it should be)
2. The sum of the histogram of bases does not equal the `TARGET_TERRITORY` (it should).

I've updated the tests to assert the target territory is equal, but this passed even before my changes because the current tests are very minimal.

**Comment by yfarjoun** [comment]
I think that @takutosato PR #658 fixes this problem (though it makes the issue you raise of the complication of the code worse)

**Comment by yfarjoun** [comment]
@tfenne can you verify that the PR that was just merged #658 actually solves this bug and therefore this PR can be closed?

**Comment by yfarjoun** [comment]
@tfenne I'm closing this as I suspect that #658 resolves the same issue reported here. please feel free to reopen (and fix the conflicts) If I'm wrong.

**Pull request closed without merging**
