### PR TITLE
Fix: getCumulative R method optimized

### PR DESCRIPTION
**Pull request by Poshi**
### Description

In this PR I optimized the R method of the script where most of the time was used.

Originally, the cumulative sum of the tails was computed over and over with the whole dataset. This lead to very long times (in the order of hours) in the calculus of an aparently quick calculus. I rewrote the method in order to do the cumulative sum by using the computed sum up to the last position, wich lowers the calculus from a quadratic approach to a linear one, drastically reducing runtime to a fes seconds when the list is large.

This serves as a workaround for a comment in [issue 1217](https://github.com/broadinstitute/picard/issues/1217). This is not the best solution for our problem, but solves the problem at hand.

As this is an optimization, with no functionality change, no tests have been neither modified nor added. Current tests should work. There are no changes in the documentation either. I'm not sure if I should check the marks in the section below...

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by Poshi** [comment]
I got some timings between original and new version with one of my problemmatics datasets:

Version | Real time | System time | User time
------- | --------- | ----------- | ---------
Original | 371m22.927s | 0m19.365s | 370m53.525s
New | 0m12.671s | 0m0.230s | 0m12.387s

**Comment by gbggrant** [comment]
@khajoue2 or @kachulis could one of you take a look at this small PR?  I'm not familiar with R.

**Review by kachulis — APPROVED** [review]
that is quite the speedup, thanks for this @Poshi!

**Comment by Poshi** [comment]
You are welcome!
The speedup usually is not so high. The original code is slow, but the common datasets contain a reduced number of entries. The issue comes when you feed it with the results of some kind of experiment that causes the insert sizes vary wildly, so you don't have a small range of sizes (few hundreds), but a broad one (millions). Then, the original quadratic approach shows up.

We should not feed this kind of data on the first place, I know. But this statistic is computed by default for all the experiments and it is not straightforward to get rid of it in specific cases.

Also, the real solution for us would be not having to generate the graph, as we don't use it for anything. But as long as the graph generation is not a bottleneck, we are fine :-) And this optimization, for sure, helps a lot :-)

**Review by khajoue2 — APPROVED** [review]
Looks good!

**Comment by Poshi** [comment]
Do I need to do something else?

**Pull request merged**
