### PR TITLE
Gg revert dsdegp 2574

### PR DESCRIPTION
**Pull request by gbggrant**
### Description

Reverts the changes in as_DSDEGP-2574_PF_percent_misreported

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by bwlang** [comment]
@gbggrant 
Seems like some big changes here but I'm not sure why from this PR description.
I'm testing an update of our bcl to fastq code for novaseq to move from 2.14.0 to 2.18.17 and found some broken fastq files. 

I'm investigating now and I'll open a separate issue once I reproduce and bisect a bit more. Meanwhile, I thought I'd check to see if you already aware of this and working on it. 

[Tue Dec 04 14:33:52 EST 2018] IlluminaBasecallsToFastq BASECALLS_DIR=/mnt/galaxy/novaseq_staging/181127_A00336_0036_AH5G5LDSXX/Data/Intensities/BaseCalls LANE=3 RUN_BARCODE=A00336 MACHINE_NAME=A00336 FLOWCELL_BARCODE=H5G5LDSXX READ_STRUCTURE=151T8B8B151T MULTIPLEX_PARAMS=/mnt/galaxy/novaseq_staging/181127_A00336_0036_AH5G5LDSXX/lane3_multiplex_params.txt NUM_PROCESSORS=4 FIRST_TILE=2676 TILE_LIMIT=1 MAX_READS_IN_RAM_PER_TILE=3000000 COMPRESS_OUTPUTS=true TMP_DIR=[/state/partition1/sge_tmp] COMPRESSION_LEVEL=1 MAX_RECORDS_IN_RAM=3000000    APPLY_EAMSS_FILTER=true FORCE_GC=true MINIMUM_QUALITY=2 INCLUDE_NON_PF_READS=true IGNORE_UNEXPECTED_BARCODES=false READ_NAME_FORMAT=CASAVA_1_8 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false

```
...
+
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFFFFFFFFFFFFF:FFFFFFF:FFFFFFFFFF
FFFFFFFFFFF
@A00336:A00336:H5G5LDSXX:3:2676:9995:5243 1:N:0:TAGTCTCGATCACGTT
CTGTTCCCACTGTGTAGAACCGCCCTTTGTTGTGTGAGTGGTAGTGATATGGTTTGTTGTTATATGGTTTTTAGTTATTGTTTTTTGGAATGTATTGTTTAGTGTTGATTTGATTAATTTGGTTGATGTTGTTTTGTTTT
TGTTTATGTAT
+
FFFFFFFFFFFFFFFFF::FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFF:FFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFF:FFFFFFFFFFFF
vG<D3><CF>      '<87><EF><F2><9A><ED>^Q!l"R<CB>|<93><FF><E5>7<AB><D9>1<C8>/<9F><DB><EF>~Z0Zn;g<8C><B2><BC><88>^H<E1>Jr<D9><F9>^N<91><80><E4> ^W^X=
t<E6>RESC>^Cv<FB>v@T0NO<B6>^NRr^C<E7><BA><FC>|  <F2>a<B2>ަ<AE><E2>ZR`<99><E9><FE><C2>(<CB>/<97><F7><ED><87>^S<F3>v<BF>%<D4><F9>:<A2>噭\ʅ<F8>N^Lv`<91><A0>E<E5>;(j<A6><81>>ԆYT~(^RkP<81>^@<EF>^W<E8><A9>D<94><F3>}<96>O<FA>lh<90><AA>S_`U<A5>^G<EE>N<B0>o<B5><E8>Ώ<AA><D7>,^M<8D>A<FE><B5><B7>H1^T<A3>D<C6><DB>y<84>(<C2>s<DA>#<AC><U+008B><FC>,<F8><A2>4\"<9D><B0>^EjESC=l^De<C5>Z5<A7>MJq4<B4>^E㗼G<90><FF><98><CC><CF><D3>Fӏ<BC>
<E9>^@䧏<E9>x<BA>lﹽ^\<CF>^X<FB>$`^\<91>k<A2><A4><E6>M<A8><E3>^A<B0>x<B8><B4>^C<B4>^T<CA>^D<B5>^E<EC>_.<B9><C9>}^BΙ<C8>'<BC>͚<82><9C><8D>^L(
<CB><D4>}><BC>t<9F>{<93><9F>^YSw<BA><BA><F6>0^M<D1>|<C1><FC><BA><BD><FF><F3>"<E4>)
<B9><C3>p<8E>G<D4>_<AA>q<C8>)<A6>if遄z1V^V
<F4>^T^O^F1<90>q^NB^]V·<84><93><E2><A8>^G皥^^<AF><AF><F8>wi^D<EE><E5><C2>К<96>^E<F2><AF>?<<DF><C4>|<E6>r<F3>%<96><CE>]<B7>"<97>%c\<EF>
<E5>R<9B>^M<䠇:<9D>*O3Ak^P\^Z-^WnT^Z<87><89>r^N`<F9>o<CC>ESC/<F1>k^C<D0>^]<B4>;<92>W<A9>C^?iU<EE>&<DD>x<CB>ޏ<AE>[le+h^Y<C5><FC><F2><B1>}<AF>b+<85>0
^N^WEN<92><DD><C8>cr9f<97>Z3<F2>t<97><B6>'<E4>F^F<CF>.c$ߍ=)<D0>^T}<E8>]h>m<A0>7<94><A6>^G<87>[<EA><B3>u<AE><A3>Ai9<BD>]߶<9F><C1>M<B9><C5>"
<B9><85>h$<B2>$<C6><E0><E1>(^S<CC><ED>^S<D1>^L+<9D>^A<88>0<8C><EE>^B<85><F5><9A><93>ej8^O-<CA>j<89>9`<9E>nDx<U+F355><BF><9C><FA>^U0<CB>^Q
<FA><C3> <E6><C7><F7><B7><9D>I<DC>T<E2><CC>ηTb<91><A8>s+EDu98r+^Y<8E><A8>^^ <85>G^@  <FB>ih^Ut<9D>fe,^]^X<B5>^]U<E8><A4><D1>V^<FF><DF>j^C
<E8><FF><FB><D4><D4>h^T<F3><8F><CD><E0><^?<ED>|<B2>b^Y^S-2<90><EF>^M^Qh^Ep<A2><DB><C1><9C>0z<C9>C<E6>X@<EB>!^X<E6><#Ĉ<DC><C9>r
M*^?<C6>F^A-2(<D3>k<E3><A1><DB>tg<AC>^G<D6><FB><B1>V^MB<FE>~<D9><DB>^Y<B7><80><A1><DB>#<B5><81>*><82><E3>^]<A7><E4>rV<85>^D<86> <F2>
```

**Comment by bwlang** [comment]
After a re-run with 2.18.7 I do see the corrupt fastq files again. 
Ill try to reproduce just before #1231 was merged (2.18.15)

**Comment by bwlang** [comment]
stilll corrupt with 2.18.15 - so my issue is probably not related to yours...

**Comment by kbergin** [comment]
To clean up this repo, we are deleting stale branches that have been merged or closed. You have a short period of time to restore this branch if needed. Thanks!

**Pull request merged**
