### PR TITLE
Extract CommandLineProgram finding/processing code for reuse.

### PR DESCRIPTION
**Pull request by cmnbroad**
### Description

Extract CommandLineProgram finding/processing code for reuse, as requested [here](https://github.com/broadinstitute/picard-private/pull/987);

#### Content
- [ x] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [x ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

### CODE REVIEW

**Comment by nh13** [comment]
@cmnbroad picard private is ... private.  Can you post the motivation for this?

**Comment by cmnbroad** [comment]
@nh13 The motivation is just to reduce the number of times the code that finds all of the CommandLinePrograms is duplicated (two in Picard, plus the one in picard-private). The picard-private part is incidental other than that it was where the request originated.

**Comment by nh13** [comment]
@cmnbroad thanks for providing some context!

**Comment by kbergin** [comment]
To clean up this repo, we are deleting stale branches that have been merged or closed. You have a short period of time to restore this branch if needed. Thanks!

**Comment by cmnbroad** [comment]
Oh wait, this one was merged. Deleting...

**Pull request merged**
