### PR TITLE
update to htsjdk 2.11.0 and fix tests that broke

### PR DESCRIPTION
**Pull request by jsotobroad**

### CODE REVIEW

**Comment by jacarey** [comment]
:+1:

**Comment by yfarjoun** [comment]
It would be good to note why we are rev'ing htsjdk. i.e. what improvements to Picard will result from this version. Could you update your commit message to reflect this?

**Comment by yfarjoun** [comment]
would it make more sense to change RecordSetBuilder to set the length of the read from the cigar, if provided?

**Comment by yfarjoun** [comment]
that hurt.

**Comment by jsotobroad** [comment]
oh errr, sure i can make a new pr, i didnt see this comment till now.  whoops

**Pull request merged**
