### PR TITLE
Adding IGNORE_MISSING_MATES option to FixMateInformation

### PR DESCRIPTION
**Pull request by nh13**

### CODE REVIEW

**Comment by nh13** [comment]
Relies on https://github.com/samtools/htsjdk/pull/338, so tests will initially fail here.

**Comment by nh13** [comment]
@yfarjoun I don't have permission to re-run travis.  Could you re-run so I can verify the tests pass and then you can merge?

**Comment by tfenne** [comment]
@nh13 I got it.  Travis is re-running.

**Comment by abaumann** [comment]
looks good, merging

**Pull request merged**
