### PR TITLE
Fixes to usage examples on gh-pages docs

### PR DESCRIPTION
**Pull request by andrewquitadamo**
I fixed the background for two usage examples (MarkDuplicates and CollectMultipleMetrics) so they match the other usage examples.
I've also standardized the indentation of the usage examples and the capitalization (Usage example vs Usage Example).

### CODE REVIEW

**Comment by vdauwera** [comment]
Hi @andrewquitadamo,

The content you've corrected is actually pulled into the webpages from the source code every time a new version is released. So the right place to make these corrections is in each tool's source code file, not here in the html pages, which will be overwritten by the next release. We can take these changes in so they'll look nice in the meantime of course.

**Comment by vdauwera** [comment]
If you'd still like us to take these in we'll need you to squash them into a single commit, by the way.

**Comment by yfarjoun** [comment]
I disagree. There's no point in taking in a change to auto-generated files.

:-1:

**Comment by andrewquitadamo** [comment]
Oops. 

If you would like I can make these fixes to the source files. I suppose a new pull request would be better for that? Let me know the best way to proceed.

**Comment by yfarjoun** [comment]
Sure, a new PR would be best. Thank-you!

**Comment by ktibbett** [comment]
@andrewquitadamo , ok to close this PR?

**Pull request closed without merging**
