### PR TITLE
Adding the COVERED action to interval list tools.

### PR DESCRIPTION
**Pull request by nh13**
Depends on a release of htsjdk: https://github.com/samtools/htsjdk/pull/877

### CODE REVIEW

**Comment by yfarjoun** [comment]
(wait for tests)

**Comment by nh13** [comment]
@yfarjoun waiting on a htsjdk release

**Comment by nh13** [comment]
@yfarjoun why isn't rebased enabled in this repository?  I would like to separate the two commits, yet not create an u-g-l-y merge commit.

**Comment by yfarjoun** [comment]
Mostly since these are new and confusing options that might get improperly
used..

**Pull request merged**
